# Generated by Django 6.0.3 on 2026-03-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
